version: "3.9"
services:
  pg:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notar
    ports:
      - "5432:5432"
    volumes:
      - ./docker/mnt/pg:/var/lib/postgresql/data
